/*
*   This workflow is to prepare fastq file using fastp. The main goal is to check the quality of the reads
*   as well as trim the reads to shorten it to as close to the length of the reference as possible on top of
*   removing adapters on the the reads. The reason is because the references used for the alignment are 50 bp
*   in length. Additional length generated by the sequencing platform per read may introduce supplementary or
*   secondary aligmemnts that will confuse the which peptide actually aligns to what.
*/

nextflow.enable.dsl=2

// process FASTP_OUT is to take in the fastq 
process PEAR_OUT{
    tag "${basename}"
    publishDir "$params.results/merged_fastq/", mode: 'copy', overwrite: true    
    input:
        tuple path(filename_r1),path(filename_r2), val(basename)
    output:
        path("*.assembled.fastq.gz"), emit: mergedFqName        
        
    script:
        """
        pear --threads ${task.cpus} \
        -f ${filename_r1} \
        -r ${filename_r2} \
        -o ${basename}; \
        gzip -9 -c ${basename}.assembled.fastq > ${basename}.assembled.fastq.gz; \

        """
}

process UNRAVEL_ASSEMBLED_NAMES{    
    publishDir "$params.results/merged_fastq/", mode: 'copy', overwrite: true
    input:
        val assembled_fastq_list
    output:
        path "assembled_names_collection.txt", emit: assembled_names_collection
    script:
        """
        for item in ${assembled_fastq_list.join(' ')}; 
        do            
            echo "\$item" >> assembled_names_collection.txt
        done

        """
}

// process UPDATE_SAMPLE_TABLE is to update the sample table with the filtered fastq file names
process UPDATE_SAMPLE_TABLE{
    publishDir "$params.results/merged_fastq/", mode: 'copy', overwrite: true
    input:
        path assembled_fastq_list
        path sample_table        
    output:
        path "assembled_sample_table.csv", emit: assembled_table
    script:
        """
        update_sample_table_huscan.py \
        -s ${sample_table} \
        -t ${assembled_fastq_list} \
        -r ${params.results}/merged_fastq \
        -o "assembled_sample_table.csv" \
        -m 'assembled'
        """
}

workflow PEARMERGE_WORKFLOW{
    take:
        sample_ch
    main:        
        println "Running PEARMERGE_WORKFLOW in huscan mode."            
            sample_ch.splitCsv(header:true)
            .map{ row -> 
                    tuple(
                        file(row.fastq_filepath), // fastq file path for r1                        
                        file(row.fastq_filepath2), // fastq file path for r2
                        (row.fastq_filepath =~ /.+\/(.+)_R1_001_filtered\.fastq\.gz/)[0][1] // extract the base name
                    )                    
                }
            .set { sample_table_ch }
        // sample_ch.view()
        PEAR_OUT(sample_table_ch)        
        UNRAVEL_ASSEMBLED_NAMES(PEAR_OUT.out.mergedFqName.toList())
        UPDATE_SAMPLE_TABLE(UNRAVEL_ASSEMBLED_NAMES.out.assembled_names_collection, sample_ch)
    emit:
        sample_info = UPDATE_SAMPLE_TABLE.out.assembled_table
}

