/*
*   This workflow is to prepare fastq file using fastp. The main goal is to check the quality of the reads
*   as well as trim the reads to shorten it to as close to the length of the reference as possible on top of
*   removing adapters on the the reads. The reason is because the references used for the alignment are 50 bp
*   in length. Additional length generated by the sequencing platform per read may introduce supplementary or
*   secondary aligmemnts that will confuse the which peptide actually aligns to what.
*/

nextflow.enable.dsl=2

// process FASTP_OUT is to take in the fastq 
process PEAR_OUT{
    tag "${basename_r1}"
    publishDir "$params.results/merged_fastq/", mode: 'copy', overwrite: true    
    input:
        tuple val(tech_id), path(filename_r1),path(filename_r2), val(basename_r1)
    output:
        // path("*.assembled.fastq.gz"), emit: mergedFqName
        tuple val(tech_id),
            val(basename_r1),
            path("*.assembled.fastq.gz"),
            emit: mergedFqTuple
    script:
        def basename = basename_r1.replaceFirst(/_R1_001$/, '')
        """
        pear --threads ${task.cpus} \
        -f ${filename_r1} \
        -r ${filename_r2} \
        -o ${basename}; \
        gzip -9 -c ${basename}.assembled.fastq > ${basename}.assembled.fastq.gz; \

        """
}

process UNRAVEL_ASSEMBLED_NAMES{    
    publishDir "$params.results/merged_fastq/", mode: 'copy', overwrite: true
    input:
        val assembled_fastq_list
    output:
        path "assembled_names_collection.txt", emit: assembled_names_collection
    script:        
        def text = assembled_fastq_list.collect { row ->"${row[2]}"}.join('\n')
        """
        printf '%s\n' '${text}' > assembled_names_collection.txt
        """
}

// process UPDATE_SAMPLE_TABLE is to update the sample table with the filtered fastq file names
process UPDATE_SAMPLE_TABLE{
    publishDir "$params.results/merged_fastq/", mode: 'copy', overwrite: true
    input:
        path assembled_fastq_list
        path sample_table        
    output:
        path "assembled_sample_table.csv", emit: assembled_table
    script:
        """
        update_sample_table_huscan.py \
        -s ${sample_table} \
        -t ${assembled_fastq_list} \
        -r ${params.results}/merged_fastq \
        -o "assembled_sample_table.csv" \
        -m 'assembled'
        """
}

workflow PEARMERGE_WORKFLOW{
    take:
        tuple_ch
        sample_ch
    main:        
        println "Running PEARMERGE_WORKFLOW in huscan mode."        
        tuple_ch
        .flatMap { all_rows -> all_rows }
        .map{ one_row -> 
                tuple(
                    one_row[0],  // tech_id
                    one_row[3],  // filename_r1                        
                    one_row[4],  // filename_r2
                    one_row[1]   // basename_r1 to be used for extracting basename
                )
        }                                                
        .set{tuple_input_ch}        
        PEAR_OUT(tuple_input_ch)
        PEAR_OUT.out.mergedFqTuple
        .toList()
            .map{
                rows -> rows.sort { a, b -> a[0] <=> b[0] } // customised comparator to tell how you want to sortt
            }.set{merged_fastq_list_ch}
        UNRAVEL_ASSEMBLED_NAMES(merged_fastq_list_ch)
        UPDATE_SAMPLE_TABLE(UNRAVEL_ASSEMBLED_NAMES.out.assembled_names_collection, sample_ch)        
    emit:
        assembled_tuple = PEAR_OUT.out.mergedFqTuple
        assembled_info = UPDATE_SAMPLE_TABLE.out.assembled_table
}

