/*
*   This workflow is to prepare fastq file using fastp. The main goal is to check the quality of the reads
*   as well as trim the reads to shorten it to as close to the length of the reference as possible on top of
*   removing adapters on the the reads. The reason is because the references used for the alignment are 50 bp
*   in length. Additional length generated by the sequencing platform per read may introduce supplementary or
*   secondary aligmemnts that will confuse the which peptide actually aligns to what.
*/

nextflow.enable.dsl=2

// process FASTP_OUT is to take in the fastq 
process FASTP_OUT{    
    tag "${basename}"
    publishDir "$params.results/filtered_fastq/", mode: 'copy', overwrite: true
    //container = 'docker.io/pdawgzgg/avarda_r_env:0.1'
    
    input:
        tuple val(tech_id),val(basename),path(filename)
    output:        
        tuple val(tech_id),
              val(basename),
              path("${basename}_filtered.fastq.gz"),
              emit: filteredTuple
        //path("*_filtered.fastq.gz"), emit: filteredFqName
        path ("*_filtered.html")
        
    script:
        """        
        fastp -t 0 \
        -i "${filename}" \
        -z 9 \
        -o "${basename}_filtered.fastq.gz" \
        -R "${basename}" \
        -j "${basename}_filtered.json" \
        -h "${basename}_filtered.html"
        """
}

process FASTP_OUT_PE{
    tag "${basename}"
    publishDir "$params.results/filtered_fastq/", mode: 'copy', overwrite: true    
    input:
        tuple val(tech_id),val(basename_r1),path(filename_r1),val(basename_r2),path(filename_r2), val(basename)
    output:
        // path("*_filtered.fastq.gz"), emit: filteredFqName
        // path ("*_filtered.html")
        // This outputs the filtered fastq in pairs within a tuple list channel
        // Each element in the tuple list looks like:
        // [basename, filtered_fastq_r1_path, filtered_fastq_r2_path]
        tuple( 
            val(basename), 
            path("${basename_r1}_filtered.fastq.gz"), 
            path("${basename_r2}_filtered.fastq.gz"), 
            emit: filteredFqName
        )
        path("${basename}_filtered.html")
    script:
        """                
        fastp \
        -z 9 \
        -R "${basename}" \
        -j "${basename}_filtered.json" \
        -h "${basename}_filtered.html" \
        --in1 "${filename_r1}" \
        --in2 "${filename_r2}" \
        --out1 "${basename_r1}_filtered.fastq.gz" \
        --out2 "${basename_r2}_filtered.fastq.gz"
        """

}

process UNRAVEL_FILTERED_NAMES{    
    // publishDir "$params.results/filtered_fastq/", mode: 'copy', overwrite: true
    input:
        val filtered_fastq_list
    output:
        path "filtered_names_collection.txt", emit: filtered_names_collection
    script:        
        """        
        printf '%s\n' ${filtered_fastq_list.collect { "'${it}'" }.join(' ')} > filtered_names_collection.txt

        """
}

process UNRAVEL_FILTERED_NAMES_PE{    
    // publishDir "$params.results/filtered_fastq/", mode: 'copy', overwrite: true
    input:
        val filtered_fastq_list
    output:
        path "filtered_names_collection.tsv", emit: filtered_names_collection
    script:
        def rows = filtered_fastq_list
        def text = rows.collect { row -> "${row[1].name}\t${row[2].name}"}.join('\n')
        """
        cat <<EOF > filtered_names_collection.tsv
        ${text}
        EOF
        """
}
        // echo ${filtered_fastq_list} | \
        // grep -o '/[^ ]*fastq.gz' | \
        // awk '/_R1_/ {r1=\$0} /_R2_/ {print r1 "\t" \$0}' > filtered_names_collection.tsv
// process UPDATE_SAMPLE_TABLE is to update the sample table with the filtered fastq file names
process UPDATE_SAMPLE_TABLE{    
    publishDir "$params.results/filtered_fastq/", mode: 'copy', overwrite: true
    input:
        path filtered_fastq_list
        path sample_table        
    output:
        path "filtered_sample_table.csv", emit: filtered_table
    script:
        """
        update_sample_table.py \
        -s ${sample_table} \
        -t ${filtered_fastq_list} \
        -r ${params.results}/filtered_fastq \
        -o "filtered_sample_table.csv"
        """
}

process UPDATE_SAMPLE_TABLE_PE{    
    publishDir "$params.results/filtered_fastq/", mode: 'copy', overwrite: true
    input:
        path filtered_fastq_csv
        path sample_table        
    output:
        path "filtered_sample_table.csv", emit: filtered_table
    script:
        """
        update_sample_table_huscan.py \
        -s ${sample_table} \
        -t ${filtered_fastq_csv} \
        -r ${params.results}/filtered_fastq \
        -o "filtered_sample_table.csv" \
        -m "filtered"
        """
}


workflow FASTP_WORKFLOW{
    take:
        sample_ch
    main:
        // Check if sample table is not default value. If it is not
        // we assume that file path for samples is provided by user in sample table
        // file and we do not add default prefix.
        // if(params.sample_table != "$baseDir/subworkflows/local/phippery/data/pan-cov-example/sample_table_with_beads_and_lib.csv"){
        //     curr_reads_prefix = ''
        // }else{
        //     curr_reads_prefix = params.reads_prefix
        // }
        // Take original sample table
        // got to extract the first column that contains all
        // the fastq file paths and then run fastp.        
        final_filtered_table_ch = Channel.empty()
        if(params.runtype == "virscan"){
            println "Running FASTP_WORKFLOW in virscan mode."
            // sample_ch = Channel.fromPath(params.sample_table)
            sample_ch
                .splitCsv(header:true)
                .map{ row -> 
                        tuple(
                            row.technical_replicate_id, 
                            (row.fastq_filepath =~ /.+\/(.+)\.fastq\.gz/)[0][1], // extract the base name of the fastq file
                            file(row.fastq_filepath) // fastq file path
                        ) 
                    }
                .set { sample_table_ch }
            // Run fastp for quality check and then collect the new filtered fastq
            // file names. After that alter the original sample table so the fastq file paths
            // are pointing to the new filtered fastq files.
            FASTP_OUT(sample_table_ch)            
            FASTP_OUT.out.filteredTuple
                .toList()
                .map{rows -> rows.sort{it[0]}.collect { it[2].name }}
                .set{filtered_fastq_list_ch}
            FASTP_OUT.out.filteredTuple.set{final_filtered_tuple_ch}
            
            UNRAVEL_FILTERED_NAMES(filtered_fastq_list_ch)
            UNRAVEL_FILTERED_NAMES.out.filtered_names_collection
                .set{collection_ch}
            
            UPDATE_SAMPLE_TABLE(collection_ch,sample_ch)
            UPDATE_SAMPLE_TABLE.out.filtered_table
                .set{final_filtered_table_ch}            
        }else if(params.runtype == "huscan"){
            println "Running FASTP_WORKFLOW in huscan mode."
            sample_ch
            .splitCsv(header:true)
            .map{ row -> 
                    tuple(
                        row.technical_replicate_id,                         
                        (row.fastq_filepath =~ /.+\/(.+)_trimmed\.fastq\.gz/)[0][1], // extract the base name including r1 tag
                        file(row.fastq_filepath), // fastq file path for r1
                        (row.fastq_filepath2 =~ /.+\/(.+)_trimmed\.fastq\.gz/)[0][1], // extract the base name including r2 tag
                        file(row.fastq_filepath2), // fastq file path for r2
                        (row.fastq_filepath =~ /.+\/(.+)_R1_001_trimmed\.fastq\.gz/)[0][1] // extract the base name
                    )                    
                }
            .set { sample_table_ch }            
            FASTP_OUT_PE(sample_table_ch)

            // toList makes the thing into a single list object not a stream of stuff (e.g. tuple)
            //UNRAVEL_FILTERED_NAMES_PE(FASTP_OUT_PE.out.filteredFqName.toList())            
            UNRAVEL_FILTERED_NAMES_PE(
                FASTP_OUT_PE.out.filteredFqName.toList().map{
                    rows -> rows.sort { a, b -> a[0] <=> b[0] } // customised comparator to tell how you want to sortt
                }
            )
            //UNRAVEL_FILTERED_NAMES_PE(FASTP_OUT_PE.out.filteredFqName.toList())
            UNRAVEL_FILTERED_NAMES_PE.out.filtered_names_collection.set{collection_ch}
            UPDATE_SAMPLE_TABLE_PE(collection_ch,sample_ch)
            final_filtered_table_ch = UPDATE_SAMPLE_TABLE_PE.out.filtered_table
        }        
    emit:
        // reminder to self
        // final_filtered_tuple_ch contains tuple that stores something like this:
        // [technical_replicate_id, base_name, fastq_filepath]
        // [BG_8, 1_XXX_8-WEGTY_S8_L001_R1_001, PATH/TO/1_XXX_8-WEGTY_S8_L001_R1_001_filtered.fastq.gz]
        filtered_tuple = final_filtered_tuple_ch 

        // this stores the filtered sample table csv which contains columns that look like:
        // fastq_filepath | control_status | technical_replicate_id | sample_source | sample_status
        // This is to be used as meta data for joining later as well as user readable file. 
        // Not to be use as direct input.
        filtered_info = final_filtered_table_ch
}

